# Generated by Django 4.1.4 on 2022-12-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Global", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Global", new_name="Global_Model",),
    ]
