# Generated by Django 4.1.4 on 2022-12-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Global", "0002_rename_global_global_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="global_model",
            name="score",
            field=models.TextField(default=" "),
        ),
        migrations.AddField(
            model_name="global_model",
            name="trace_back",
            field=models.TextField(default=" "),
        ),
    ]
