# Generated by Django 4.1.4 on 2022-12-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Global", "0003_global_model_score_global_model_trace_back"),
    ]

    operations = [
        migrations.AlterField(
            model_name="global_model", name="score", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="global_model", name="trace_back", field=models.TextField(),
        ),
    ]
