# Generated by Django 4.1.4 on 2022-12-15 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Global", "0005_alter_global_model_score_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="global_model", old_name="score", new_name="score_matrix",
        ),
        migrations.RenameField(
            model_name="global_model",
            old_name="trace_back",
            new_name="traceback_matrix",
        ),
    ]
