# Generated by Django 4.1.4 on 2022-12-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Local_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq1", models.CharField(max_length=100)),
                ("seq2", models.CharField(max_length=100)),
                ("score_matrix", models.TextField(null=True)),
                ("best_score", models.IntegerField()),
                ("alignment1", models.CharField(max_length=100)),
                ("alignment2", models.CharField(max_length=100)),
            ],
        ),
    ]
