# Generated by Django 2.2.28 on 2023-01-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq1', models.CharField(max_length=200)),
                ('seq2', models.CharField(max_length=100)),
                ('score_matrix', models.TextField(null=True)),
                ('best_score', models.IntegerField()),
                ('alignment1', models.CharField(max_length=100)),
                ('alignment2', models.CharField(max_length=100)),
            ],
        ),
    ]
